### ISSUE TITLE
(Database) Create algorithm to generate data for date select histogram

### ISSUE THREAD

**Issue by CristianFelix** [CristianFelix/email-analytics#12]

**Comment by CristianFelix** [comment]
A good tool to access MongoDb is called RoboMongo

**Comment by lithoformer** [comment]
db.email.aggregate(
        [
        { $unwind : "$Messages" },
        { $project : { date : { $substr: [ "$Messages.date", 0, 10 ]}, received : { $cond : { if : { $eq: ["$Messages.direction", "received"]}, then: 1, else: 0}}, sent : { $cond : { if : { $eq: ["$Messages.direction", "sent"]}, then: 1, else: 0}}}},  
        { $group : { _id: "$date", received:{$sum:"$received"}, sent : {$sum:"$sent"}}},
        { $project : { _id : 0, date : "$_id", received : 1, sent : 1 }},
        { $sort : { date : 1 }}
])
