### ISSUE TITLE
(database) Create a function to return the time to answer

### ISSUE THREAD

**Issue by CristianFelix** [CristianFelix/email-analytics#17]
timToAnswer: [{
    domain: "apple.com",
    You: 20,
    Then: 154,
    contacts: [{
Name: "Tim cook", 
email: "tim@apple.com", 
You: 67, 
Then: 1254 }, {...}]
}, {...}]

**Comment by lithoformer** [comment]
db.email.aggregate(
[
{ $unwind : "$Messages" },
{ $match : { "Messages.direction": "sent" } },
{ $unwind : "$Messages.to" },
{ $project : { _id: 1, Domain : "$Messages.to.domain", Contacts : {email: "$Messages.to.email", name: "$Messages.to.Name", date: "$Messages.date", replied:"$Messages.replied"},time : { $subtract : [ "$Messages.replied", "$Messages.date"]}}},
{ $group : {_id : "$Domain", Them: {$avg : "$time"}, Contacts : {$addToSet : "$Contacts"}}},
{ $project : { _id: 0, domain : "$_id", them : {$divide: ["$Them",60000]}, Contacts : "$Contacts"}},
{ $unwind: "$Contacts" },
{ $project : { _id: 0, domain : "$domain", Them : "$them", Contacts : {email: "$Contacts.email", name: "$Contacts.name", time: { $subtract : [ "$Contacts.replied", "$Contacts.date"]}}}},
{ $group : { _id : { domain : "$domain", Them : "$Them", Contacts : "$Contacts"}}},
{ $group : { _id : "$_id.Contacts.name", ThemContact : {$avg : "$_id.Contacts.time"}, email :{$addToSet :"$_id.Contacts.email"}, domain : {$addToSet: "$_id.domain"}, Them : {$addToSet: "$_id.Them"}}},
{ $project : { _id : 1, themContact : {$divide : ["$ThemContact",60000]}, email : "$email", domain : "$domain", Them : "$Them"}},
{ $group : { _id : { domain : "$domain", Them : "$Them", Contacts: { Name : "$_id", email : "$email", themContact : "$themContact"}}}},
{ $group : { _id : "$_id.domain", Them : {$addToSet :"$_id.Them"}, Contacts : {$addToSet : "$_id.Contacts"}}}
])

**Comment by lithoformer** [comment]
db.email.aggregate(
[
{ $unwind : "$Messages" },
{ $match : { "Messages.direction": "received" } },
{ $project : { _id: 1, Domain : "$Messages.from.domain", Contacts : {email: "$Messages.from.email", name: "$Messages.from.Name", date: "$Messages.date", replied:"$Messages.replied"},time : { $subtract : [ "$Messages.replied", "$Messages.date"]}}},
{ $group : {_id : "$Domain", You: {$avg : "$time"}, Contacts : {$addToSet : "$Contacts"}}},
{ $project : { _id: 0, domain : "$_id", you : {$divide: ["$You",60000]}, Contacts : "$Contacts"}},
{ $unwind: "$Contacts" },
{ $project : { _id: 0, domain : "$domain", You : "$you", Contacts : {email: "$Contacts.email", name: "$Contacts.name", time: { $subtract : [ "$Contacts.replied", "$Contacts.date"]}}}},
{ $group : { _id : { domain : "$domain", You : "$You", Contacts : "$Contacts"}}},
{ $group : { _id : "$_id.Contacts.name", YouContact : {$avg : "$_id.Contacts.time"}, email :{$addToSet :"$_id.Contacts.email"}, domain : {$addToSet: "$_id.domain"}, You : {$addToSet: "$_id.You"}}},
{ $project : { _id : 1, youContact : {$divide : ["$YouContact",60000]}, email : "$email", domain : "$domain", You : "$You"}},
{ $group : { _id : { domain : "$domain", You : "$You", Contacts: { Name : "$_id", email : "$email", youContact : "$youContact"}}}},
{ $group : { _id : "$_id.domain", You : {$addToSet :"$_id.You"}, Contacts : {$addToSet : "$_id.Contacts"}}}
])

**Comment by lithoformer** [comment]
Cristian: The layout is correct, but the data format is not as you requested as I'm not sure how to set arrays as fields and fields as arrays.  Sorry, can you work with this?

**Comment by CristianFelix** [comment]
Sure, no problem, I already have data, so will be easy to finish it
