### ISSUE TITLE
(database) Create a function to get the 20 most frequent contacts

### ISSUE THREAD

**Issue by CristianFelix** [CristianFelix/email-analytics#18]
frequentContacts: [{
    Sent: [{
    domain: "apple.com",
    Count: 20,
    Contacts: [{
Name: "Tim cook", 
email: "tim@apple.com", 
Count: 14
}, {...}],
Received: [{
    domain: "apple.com",
    Count: 20,
    Contacts: [{
Name: "Tim cook", 
email: "tim@apple.com", 
Count: 14
}, {...}]

}]

**Comment by CristianFelix** [comment]
Good,
Just three things. 
1) You have to order count by -1 to be decrescent, otherwise the result will be the 20 less frequent contacts

2) The email collection doesn’t have the field email, it has the field Messages, that has the fields “from” and “to” with the contacts, and then you have the email field in each contact. You have to unwind these fields.

3) also remember that you have to count “sent”and “received” emails separated.

**Comment by lithoformer** [comment]
db.email.aggregate(
        [
        { $unwind : "$Messages" },
        { $match : { "Messages.direction": "sent" } },
        { $unwind : "$Messages.to" },
        { $group : {"_id" : "$Messages.id", domains : {$addToSet: "$Messages.to.domain" }, contacts: {$addToSet: "$Messages.to"}}},
        { $unwind : "$domains" },
        { $group : {_id: "$domains", count: {$sum:1},contacts:{$push: "$contacts"}}},
        { $unwind: "$contacts" },
        { $unwind: "$contacts" },
        { $group : {_id: {domain: "$_id" , countD: "$count", contact: "$contacts"},countC:{$sum:1}}},
        { $project : { domain : "$_id.domain", countD: "$_id.countD",Contacts : {email: "$_id.contact.email",name:"$_id.contact.Name", count: "$countC"}}},
        { $group : { _id: { domain : "$domain", countD:"$countD"},contacts:{$addToSet:"$Contacts"}}},
        { $sort : { "Contacts.count" : -1 } },
        { $limit : 20 },
])

**Comment by lithoformer** [comment]
db.email.aggregate(
        [
        { $unwind : "$Messages" },
        { $match : { "Messages.direction": "received" } },
        { $group : {"_id" : "$Messages.id", domains : {$addToSet: "$Messages.from.domain" }, contacts: {$addToSet: "$Messages.from"}}},
        { $unwind : "$domains" },
        { $group : {_id: "$domains", count: {$sum:1},contacts:{$push: "$contacts"}}},
        { $unwind: "$contacts" },
        { $unwind: "$contacts" },
        { $group : {_id: {domain: "$_id" , countD: "$count", contact: "$contacts"},countC:{$sum:1}}},
        { $project : { domain : "$_id.domain", countD: "$_id.countD",Contacts : {email: "$_id.contact.email",name:"$_id.contact.Name", count: "$countC"}}},
        { $group : { _id: { domain : "$domain", countD:"$countD"},contacts:{$addToSet:"$Contacts"}}},
        { $sort : { "Contacts.count" : -1 } },
        { $limit : 20 },
])
